development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE'] %>
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV.fetch('MYSQL_HOST') { 'localhost' } %>

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE'] %>
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV.fetch('MYSQL_HOST') { 'localhost' } %>
